export type RegistrarModuleGroup = "MVP" | "Add-on";

export type RegistrarModule = {
  id: string;
  label: string;
  path: string;
  group: RegistrarModuleGroup;
  purpose: string;
  status: "Live" | "Blueprint";
  highlights: string[];
  workflows: string[];
};

export type RegistrarModuleFunction = {
  name: string;
  description: string;
};

export const registrarModules: RegistrarModule[] = [
  {
    id: "dashboard",
    label: "Registrar Dashboard",
    path: "/",
    group: "MVP",
    purpose: "Daily registrar overview for enrollment, students, requests, transfers, documents, and alerts.",
    status: "Live",
    highlights: ["Total active students", "New applications", "Pending enrollment", "Document requests", "Incomplete requirements"],
    workflows: ["Review today's applications", "Track incomplete requirements", "Monitor movement and enrollment status"],
  },
  {
    id: "finance-dashboard",
    label: "Finance Dashboard",
    path: "/finance",
    group: "MVP",
    purpose: "Manage payments, invoices, budget tracking, and financial analytics.",
    status: "Live",
    highlights: ["Total Revenue", "Outstanding Balances", "Collection Rate", "Recent Transactions"],
    workflows: ["Track daily collections", "Review employee payroll", "Monitor annual budget"],
  },
  {
    id: "student-registration",
    label: "Student Registration",
    path: "/registration",
    group: "MVP",
    purpose: "Manual student registration with learner, guardian, placement, document, medical, and fee details.",
    status: "Live",
    highlights: ["Learner information", "Parent and guardian contacts", "Previous school", "Required documents", "Medical notes"],
    workflows: ["Create draft registration", "Submit for registrar review", "Mark approved, rejected, or incomplete"],
  },
  {
    id: "enrollment-management",
    label: "Enrollment Management",
    path: "/enrollment",
    group: "MVP",
    purpose: "Official enrollment per school year, academic level, section, learner type, and enrollment status.",
    status: "Live",
    highlights: ["Enroll student", "Assign academic level", "Assign section", "Set student type", "Bulk enrollment"],
    workflows: ["Validate requirements", "Assign class placement", "Set Officially Enrolled, Pending, Dropped, Transferred Out, Graduated, or Inactive"],
  },
  {
    id: "student-masterlist",
    label: "Student Masterlist",
    path: "/students",
    group: "MVP",
    purpose: "Central list of enrolled, pending, inactive, transferred, and graduated learners.",
    status: "Live",
    highlights: ["School year filter", "Academic level filter", "Section filter", "Status filter", "Export list"],
    workflows: ["View profile", "Edit student", "Print profile", "Bulk update", "Archive inactive records"],
  },
  {
    id: "learner-profile",
    label: "Learner Profile",
    path: "/registrar/learner-profile",
    group: "MVP",
    purpose: "Full student profile with personal, family, academic, contact, document, request, movement, and audit records.",
    status: "Live",
    highlights: ["Overview", "Personal info", "Family info", "Enrollment history", "System logs"],
    workflows: ["Open learner record", "Review document status", "Inspect movement history", "Audit profile edits"],
  },
  {
    id: "documents-management",
    label: "Documents Management",
    path: "/registrar/documents-management",
    group: "MVP",
    purpose: "Upload, verify, reject, track, and release learner requirements.",
    status: "Live",
    highlights: ["Birth certificate", "Form 137", "Form 138", "Good moral", "Transfer credentials"],
    workflows: ["Mark submitted", "Verify document", "Reject unclear copy", "Flag missing or expired requirements"],
  },
  {
    id: "sections-class-assignment",
    label: "Sections & Class Assignment",
    path: "/registrar/sections-class-assignment",
    group: "MVP",
    purpose: "Organize learners into sections, advisers, academic levels, and class groups.",
    status: "Live",
    highlights: ["Create section", "Assign adviser", "Assign students", "Move student", "Capacity limit"],
    workflows: ["Create section per academic level", "Assign adviser", "Print or export class list"],
  },
  {
    id: "academic-records",
    label: "Academic Records",
    path: "/registrar/academic-records",
    group: "MVP",
    purpose: "Official grades history, report cards, previous school records, academic standing, and locked final records.",
    status: "Blueprint",
    highlights: ["Grade history", "Previous records", "Report card upload", "Academic summary", "Final record lock"],
    workflows: ["Encode previous records", "Generate academic summary", "Print official records"],
  },
  {
    id: "reports-analytics",
    label: "Reports & Analytics",
    path: "/reports",
    group: "MVP",
    purpose: "Enrollment, masterlist, movement, document compliance, gender count, age profile, and section reports.",
    status: "Live",
    highlights: ["Enrollment report", "Masterlist report", "Document compliance", "Learner movement", "Export PDF/Excel/CSV"],
    workflows: ["Filter report", "Preview totals", "Export printable output"],
  },
  {
    id: "registrar-settings",
    label: "Registrar Settings",
    path: "/registrar/registrar-settings",
    group: "MVP",
    purpose: "Configure school years, academic levels, sections, statuses, document types, enrollment rules, IDs, and workflows.",
    status: "Live",
    highlights: ["Academic year setup", "Active year control", "Enrollment window", "Terms and quarters", "Rollover readiness"],
    workflows: ["Configure current academic year", "Open or pause registration intake", "Prepare next-year rollover"],
  },
  {
    id: "online-registration-review",
    label: "Online Registration Review",
    path: "/registrar/online-registration-review",
    group: "Add-on",
    purpose: "Review, approve, reject, request correction, duplicate-check, and convert online applications.",
    status: "Blueprint",
    highlights: ["Application list", "Document review", "Correction request", "Duplicate check", "Convert to learner record"],
    workflows: ["Review submitted application", "Approve or reject", "Move approved learner to enrollment"],
  },
  {
    id: "document-requests",
    label: "Document Requests",
    path: "/registrar/document-requests",
    group: "Add-on",
    purpose: "Handle certificate, Form 137, Form 138, good moral, completion, graduation, and transfer document requests.",
    status: "Blueprint",
    highlights: ["Request review", "Approval", "Document preparation", "Release tracking", "Claim status"],
    workflows: ["Review request", "Approve", "Prepare document", "Mark ready for release", "Mark released"],
  },
  {
    id: "transfers-management",
    label: "Transfers Management",
    path: "/registrar/transfers-management",
    group: "Add-on",
    purpose: "Process incoming transferees and outgoing learner transfers with documents and clearance checks.",
    status: "Blueprint",
    highlights: ["Register transferee", "Map academic level", "Clearance check", "Destination school", "Transferred out status"],
    workflows: ["Validate transfer credentials", "Approve enrollment", "Generate outgoing documents"],
  },
  {
    id: "promotion-retention",
    label: "Promotion & Retention",
    path: "/registrar/promotion-retention",
    group: "Add-on",
    purpose: "End-of-year promotion, retention, incomplete marking, and locked school-year records.",
    status: "Blueprint",
    highlights: ["Review final grades", "Promote", "Retain", "Mark incomplete", "Bulk promotion"],
    workflows: ["Review eligibility", "Promote or retain learner", "Generate promotion report"],
  },
  {
    id: "graduation-completion",
    label: "Graduation / Completion",
    path: "/registrar/graduation-completion",
    group: "Add-on",
    purpose: "Manage completers, graduates, eligibility, certificates, final records, and alumni conversion.",
    status: "Blueprint",
    highlights: ["Candidate list", "Requirement check", "Completion approval", "Certificates", "Alumni conversion"],
    workflows: ["Check requirements", "Approve completion", "Lock final academic record"],
  },
  {
    id: "learner-movement",
    label: "Learner Movement",
    path: "/registrar/learner-movement",
    group: "Add-on",
    purpose: "Track enrolled, dropped, transferred, returned, inactive, promoted, retained, and graduated learners.",
    status: "Blueprint",
    highlights: ["New enrollee", "Continuing student", "Transferee in", "Dropped", "Returned"],
    workflows: ["Record movement", "Attach reason", "Use movement data in compliance reports"],
  },
  {
    id: "deped-compliance-forms",
    label: "DepEd / Compliance Forms",
    path: "/registrar/deped-compliance-forms",
    group: "Add-on",
    purpose: "Generate SF1, SF2, SF3, SF5, SF9, SF10, enrollment summaries, and learner movement reports.",
    status: "Blueprint",
    highlights: ["SF1", "SF2", "SF5", "SF9", "SF10"],
    workflows: ["Select school year", "Generate form", "Export printable compliance output"],
  },
  {
    id: "id-qr-management",
    label: "ID / QR Management",
    path: "/registrar/id-qr-management",
    group: "Add-on",
    purpose: "Generate IDs, QR codes, barcodes, replacement cards, attendance-linked identifiers, and ID templates.",
    status: "Blueprint",
    highlights: ["Student ID", "QR code", "Barcode", "Batch print", "Template designer"],
    workflows: ["Generate learner ID", "Print by section", "Deactivate old QR on replacement"],
  },
  {
    id: "import-export",
    label: "Import / Export",
    path: "/registrar/import-export",
    group: "Add-on",
    purpose: "Import learners, grade history, and document lists from Excel/CSV; export masterlists and reports.",
    status: "Blueprint",
    highlights: ["Import students", "Import grade history", "Export masterlist", "Download template", "Validation checker"],
    workflows: ["Upload file", "Validate rows", "Preview errors", "Import clean records"],
  },
  {
    id: "notifications-messaging",
    label: "Notifications & Messaging",
    path: "/registrar/notifications-messaging",
    group: "Add-on",
    purpose: "Send enrollment, document, clearance, approval, and system notices to students, parents, teachers, finance, and admin.",
    status: "Blueprint",
    highlights: ["Parent reminders", "Teacher messages", "Finance clearance", "Admin escalation", "Announcements"],
    workflows: ["Choose recipient group", "Send reminder", "Track notification history"],
  },
];

export function getRegistrarModuleByPath(pathname: string) {
  return registrarModules.find((module) => module.path === pathname);
}

export function getRegistrarModuleById(id: string) {
  return registrarModules.find((module) => module.id === id);
}

export function getRegistrarModuleFunctions(id: string): RegistrarModuleFunction[] {
  return registrarModuleFunctions[id] ?? [];
}

const registrarModuleFunctions: Record<string, RegistrarModuleFunction[]> = {
  "documents-management": [
    { name: "Document Checklist", description: "Show required documents per academic level, student type, and school year." },
    { name: "Upload Student Document", description: "Upload birth certificate, report card, good moral, transfer credentials, ID photo, and other files." },
    { name: "Verify Document", description: "Mark submitted documents as verified after registrar checking." },
    { name: "Reject Document", description: "Reject unclear, wrong, expired, or invalid documents with remarks." },
    { name: "Missing Requirements Tracker", description: "List learners with incomplete requirements." },
    { name: "Document Preview", description: "Preview PDF and image files without downloading." },
    { name: "Document Version History", description: "Keep old and updated submitted document copies." },
    { name: "Request Resubmission", description: "Notify the learner or parent to submit or correct a document." },
    { name: "Bulk Document Update", description: "Update document status for multiple learners." },
    { name: "Print / Download Documents", description: "Print or download selected learner documents." },
    { name: "Secure Access Control", description: "Restrict sensitive records to authorized users." },
    { name: "Document Audit Logs", description: "Track who uploaded, viewed, verified, edited, or deleted a document." },
  ],
  "sections-class-assignment": [
    { name: "Create Section", description: "Add a new section per school year and academic level." },
    { name: "Edit Section", description: "Update section name, capacity, academic level, room, and adviser." },
    { name: "Assign Class Adviser", description: "Link a teacher or adviser to a section." },
    { name: "Assign Students to Section", description: "Add enrolled learners to a section." },
    { name: "Bulk Assign Students", description: "Assign many learners at once." },
    { name: "Move Student to Another Section", description: "Transfer a learner from one section to another." },
    { name: "Section Capacity Limit", description: "Set maximum learners per section." },
    { name: "Unassigned Students List", description: "Show learners not yet assigned to a section." },
    { name: "Class List View", description: "View all learners inside a section." },
    { name: "Print Class List", description: "Generate a printable class list for the adviser." },
    { name: "Export Section List", description: "Export section lists to Excel, PDF, or CSV." },
    { name: "Gender Count per Section", description: "Show male and female count per section." },
    { name: "Section History", description: "Track section changes per learner." },
    { name: "Conflict Checker", description: "Prevent duplicate assignment or over-capacity sections." },
  ],
  "academic-records": [
    { name: "View Academic History", description: "Show grades and official records by school year." },
    { name: "Encode Previous School Records", description: "Add grades from previous schools for transferees." },
    { name: "View Report Card Records", description: "Show Form 138 or report card data." },
    { name: "View Permanent Record", description: "Show Form 137 or SF10-style academic record." },
    { name: "Upload Academic Documents", description: "Attach scanned report cards or certificates." },
    { name: "Validate Final Grades", description: "Check submitted final grades before locking." },
    { name: "Set Academic Standing", description: "Mark learners as passed, failed, incomplete, retained, or promoted." },
    { name: "Lock Final Records", description: "Prevent editing after finalization." },
    { name: "Request Grade Correction", description: "Send correction requests to teachers or admin." },
    { name: "Print Academic Record", description: "Print the learner academic summary." },
    { name: "Generate Report Card", description: "Generate printable learner card or report." },
    { name: "Academic Remarks", description: "Add registrar remarks and notes." },
    { name: "Audit Trail", description: "Track changes to official academic records." },
  ],
  "reports-analytics": [
    { name: "Enrollment Summary Report", description: "Count learners by academic level, section, status, and school year." },
    { name: "Student Masterlist Report", description: "Generate the full learner list." },
    { name: "Section Population Report", description: "Show number of learners per section." },
    { name: "Gender Count Report", description: "Count male and female learners." },
    { name: "Age Profile Report", description: "Show age distribution per academic level." },
    { name: "New Students Report", description: "List newly registered learners." },
    { name: "Transferee Report", description: "Report incoming and outgoing transferees." },
    { name: "Dropped Students Report", description: "List dropped or inactive learners." },
    { name: "Graduation Report", description: "List completers and graduates." },
    { name: "Promotion Report", description: "List promoted and retained learners." },
    { name: "Missing Documents Report", description: "Show learners with incomplete requirements." },
    { name: "Document Request Report", description: "Track requested, pending, and released documents." },
    { name: "Learner Movement Report", description: "Track enrolled, transferred, dropped, returned, and graduated learners." },
    { name: "Export to PDF", description: "Download reports as PDF." },
    { name: "Export to Excel/CSV", description: "Download spreadsheet-ready reports." },
    { name: "Print Report", description: "Render print-ready report layouts." },
    { name: "Charts & Graphs", description: "Visualize registrar dashboard analytics." },
  ],
  "registrar-settings": [
    { name: "School Year Setup", description: "Add and manage school years." },
    { name: "Term / Quarter Setup", description: "Configure quarters, semesters, or grading periods." },
    { name: "Grade Level Setup", description: "Add Kinder, Grade 1-12, college levels, and other academic levels." },
    { name: "Section Setup", description: "Configure section names and limits." },
    { name: "Student Status Setup", description: "Manage statuses like enrolled, pending, dropped, and transferred." },
    { name: "Student Number Format", description: "Configure auto-generated learner number or LRN format." },
    { name: "Document Type Setup", description: "Define required document types." },
    { name: "Enrollment Rules", description: "Set required fields and validation rules." },
    { name: "Document Checklist Rules", description: "Require documents per learner type or academic level." },
    { name: "ID Template Settings", description: "Configure learner ID design." },
    { name: "Certificate Templates", description: "Manage templates for certificates and forms." },
    { name: "Approval Workflow", description: "Set approvers for registration, transfers, and requests." },
    { name: "Registrar Permissions", description: "Control which staff can access each function." },
    { name: "Data Privacy Settings", description: "Protect sensitive learner information." },
    { name: "Archive Settings", description: "Configure inactive and old learner record handling." },
  ],
  "online-registration-review": [
    { name: "View Online Applications", description: "See all submitted online applications." },
    { name: "Application Details View", description: "Open full applicant details." },
    { name: "Duplicate Student Checker", description: "Check duplicate name, LRN, birthdate, or email." },
    { name: "Review Uploaded Documents", description: "Check files submitted online." },
    { name: "Approve Application", description: "Move an applicant to the enrollment process." },
    { name: "Reject Application", description: "Decline an application with a reason." },
    { name: "Return for Correction", description: "Ask the applicant to fix wrong or missing details." },
    { name: "Set Application Status", description: "Set pending, approved, rejected, or incomplete status." },
    { name: "Convert to Student Record", description: "Create the official learner profile." },
    { name: "Assign Preliminary Grade Level", description: "Set the expected academic level." },
    { name: "Notify Parent/Student", description: "Send the application result notification." },
    { name: "Application Timeline", description: "Track every action made on the application." },
  ],
  "document-requests": [
    { name: "Create Document Request", description: "Add a request manually or from the parent/student portal." },
    { name: "Request Type Selection", description: "Select Certificate of Enrollment, Good Moral, Form 137, Form 138, and others." },
    { name: "Review Request", description: "Check if the learner is eligible to receive the document." },
    { name: "Approve Request", description: "Approve document preparation." },
    { name: "Reject Request", description: "Reject a request with remarks." },
    { name: "Generate Document", description: "Auto-generate certificates or forms from templates." },
    { name: "Document Queue", description: "List pending, processing, ready, and released requests." },
    { name: "Release Document", description: "Mark a document as released or claimed." },
    { name: "Claimant Details", description: "Record who claimed the document." },
    { name: "Print Document", description: "Print the official copy." },
    { name: "Digital Copy Download", description: "Provide downloadable copies when allowed." },
    { name: "Request History", description: "Track all document requests per learner." },
    { name: "Notification to Parent/Student", description: "Notify when a document is ready." },
  ],
  "transfers-management": [
    { name: "Incoming Transfer Registration", description: "Register transferees from another school." },
    { name: "Previous School Details", description: "Record old school name, address, and completed grade." },
    { name: "Transfer Document Upload", description: "Upload Form 137, Form 138, good moral, and transfer certificate." },
    { name: "Evaluate Grade Placement", description: "Determine correct academic level placement." },
    { name: "Approve Incoming Transfer", description: "Allow the transferee to continue enrollment." },
    { name: "Outgoing Transfer Request", description: "Process learner transfer to another school." },
    { name: "Clearance Checking", description: "Check academic, document, and finance clearance if enabled." },
    { name: "Prepare Transfer Documents", description: "Generate required transfer documents." },
    { name: "Record Destination School", description: "Save the school where the learner transferred." },
    { name: "Mark as Transferred Out", description: "Update learner enrollment status." },
    { name: "Transfer History", description: "View the full transfer record." },
    { name: "Transfer Report", description: "Generate incoming and outgoing transfer reports." },
  ],
  "promotion-retention": [
    { name: "Promotion Eligibility Check", description: "Check if the learner passed required subjects." },
    { name: "Review Final Grades", description: "View final academic performance." },
    { name: "Promote Student", description: "Move the learner to the next academic level." },
    { name: "Retain Student", description: "Keep the learner in the same academic level." },
    { name: "Mark Incomplete", description: "Mark the learner with lacking requirements or grades." },
    { name: "Bulk Promotion by Section", description: "Promote a whole section." },
    { name: "Bulk Promotion by Grade Level", description: "Promote eligible learners in an academic level." },
    { name: "Generate Promotion List", description: "Create a list of promoted learners." },
    { name: "Generate Retention List", description: "Create a list of retained learners." },
    { name: "Promotion Remarks", description: "Add notes for each learner." },
    { name: "Lock Promotion Result", description: "Prevent changes after final approval." },
    { name: "Promotion History", description: "Track promotion records per school year." },
  ],
  "graduation-completion": [
    { name: "Graduation Candidate List", description: "List learners eligible for graduation or completion." },
    { name: "Check Academic Requirements", description: "Verify final grades and completion status." },
    { name: "Check Document Requirements", description: "Verify required documents are complete." },
    { name: "Check Clearance Status", description: "Confirm all clearance requirements." },
    { name: "Approve Candidate", description: "Mark the learner as approved for graduation." },
    { name: "Hold Candidate", description: "Mark the learner as not yet cleared." },
    { name: "Generate Completion Certificate", description: "Create certificates for completers." },
    { name: "Generate Graduation Certificate", description: "Create graduation certificates." },
    { name: "Final Academic Record Locking", description: "Lock final records after approval." },
    { name: "Graduation Masterlist", description: "Generate the official graduate list." },
    { name: "Move to Alumni Records", description: "Convert learner status to alumni or graduated." },
    { name: "Graduation Report", description: "Export graduation and completion summary." },
  ],
  "learner-movement": [
    { name: "Record Learner Movement", description: "Add movement events manually or automatically." },
    { name: "Movement Type Selection", description: "Select new, continuing, transferred in/out, dropped, returned, promoted, retained, or graduated." },
    { name: "Movement Date", description: "Record the effective date of status change." },
    { name: "Movement Reason", description: "Add reason for transfer, drop, return, or status change." },
    { name: "Student Status History", description: "View the full status timeline." },
    { name: "Dropped Student Tracking", description: "Track learners who stopped attending." },
    { name: "Returnee Tracking", description: "Track learners who came back." },
    { name: "Movement Approval", description: "Require approval for sensitive status changes." },
    { name: "Movement Reports", description: "Generate learner movement reports." },
    { name: "Undo / Correction Request", description: "Request correction for wrong movement entries." },
    { name: "Audit Trail", description: "Track who updated learner movement." },
  ],
  "deped-compliance-forms": [
    { name: "Generate SF1 / School Register", description: "Generate the learner list per section." },
    { name: "Generate SF2 / Attendance Summary", description: "Generate attendance-related reports when connected to attendance." },
    { name: "Generate SF5 / Promotion Report", description: "Generate promotion and level of proficiency reports." },
    { name: "Generate SF9 / Report Card", description: "Generate learner progress report cards." },
    { name: "Generate SF10 / Permanent Record", description: "Generate learner permanent academic records." },
    { name: "Enrollment Summary Form", description: "Count learners per academic level and section." },
    { name: "Learner Movement Form", description: "Report learner status changes." },
    { name: "Compliance Data Validation", description: "Check missing LRN, birthdate, gender, section, adviser, and other fields." },
    { name: "Form Template Manager", description: "Manage school form templates." },
    { name: "Printable Form Layout", description: "Render print-ready official layouts." },
    { name: "Export Form to Excel/PDF", description: "Download compliance forms." },
    { name: "Signature Section", description: "Add prepared by, checked by, and approved by fields." },
  ],
};
